apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-app-env-configmap
  labels:
    app: laravel-app
data:
  APP_NAME: "Laravel"
  APP_URL: "http://localhost"

  DB_CONNECTION: "mysql"
  DB_HOST: "mysql-service.default"

  REDIS_CLIENT: "predis"
  REDIS_HOST: "redis-service.default"

  SESSION_DRIVER: "redis"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  default.conf: |
    server {
        listen 80;
        listen [::]:80;
        server_name localhost; # Changed from "example.com" to "localhost"
        root /app/public; # Changed from "/srv/example.com/public" to "/app/public"

        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-Content-Type-Options "nosniff";

        index index.php;

        charset utf-8;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location = /favicon.ico { access_log off; log_not_found off; }
        location = /robots.txt  { access_log off; log_not_found off; }

        error_page 404 /index.php;

        location ~ \.php$ {
            fastcgi_pass 127.0.0.1:9000; # Changed from "unix:/var/run/php/php8.0-fpm.sock" to "127.0.0.1:9000"
            fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
            include fastcgi_params;
        }

        location ~ /\.(?!well-known).* {
            deny all;
        }
    }
