apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app-deployment
  labels:
    app: laravel-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      initContainers:
        - name: init-laravel-app
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          envFrom:
            - configMapRef:
                name: laravel-app-env-configmap
            - secretRef:
                name: laravel-app-env-secret
          volumeMounts:
            - name: laravel-app-data
              mountPath: /data
          command: ["/bin/sh"]
          args:
            - -c
            - |
              php artisan config:cache
              php artisan route:cache
              php artisan view:cache
              php artisan event:cache
              cp -a /app/. /data
              chmod -R 777 /data/bootstrap/cache
              chmod -R 777 /data/storage
              chmod -R 777 /data/vendor
              php artisan migrate --force

      containers:
        - name: laravel-app
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          envFrom:
            - configMapRef:
                name: laravel-app-env-configmap
            - secretRef:
                name: laravel-app-env-secret
          volumeMounts:
            - name: laravel-app-data
              mountPath: /app
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "200m"

        - name: nginx
          image: nginx:1.22-alpine
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: laravel-app-data
              mountPath: /app
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "200m"
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 80

      volumes:
        - name: laravel-app-data
          emptyDir: {}

        - name: nginx-config
          configMap:
            name: nginx-configmap
