apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: tkordicfpmoz/smart_sum_parking
  newTag: latest

resources:
- configmap.yaml
- deployment.yaml
- secret.yaml
- service.yaml
